import random
import time
import sys


def tim():
    print("")
    
def print1by1(text, delay=.035):
    for c in text:
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(delay)
    print

def descramble():
    print(code)
    code.replace("w", "a")
    print(code)
    print1by1(code)
    print("\n")
    time.sleep(60)
    tim()
    code.replace("h", "b")
    print1by1(code)
    print("\n")
    tim()
    code.replace("i", "c")
    print1by1(code)
    print("\n")
    tim()
    code.replace("t", "d")
    print1by1(code)
    print("\n")
    tim()
    code.replace("e", "e")
    print1by1(code)
    print("\n")
    tim()
    code.replace("b", "f")
    print1by1(code)
    print("\n")
    tim()
    code.replace("o", "g")
    print1by1(code)
    print("\n")
    tim()
    code.replace("a", "h")
    print1by1(code)
    print("\n")
    tim()
    code.replace("r", "i")
    print1by1(code)
    print("\n")
    tim()
    code.replace("d", "j")
    print1by1(code)
    print("\n")
    tim()
    code.replace("s", "k")
    print1by1(code)
    print("\n")
    tim()
    code.replace("c", "l")
    print1by1(code)
    print("\n")
    tim()
    code.replace("f", "m")
    print1by1(code)
    print("\n")
    tim()
    code.replace("g", "n")
    print1by1(code)
    print("\n")
    tim()
    code.replace("j", "o")
    print1by1(code)
    print("\n")
    tim()
    code.replace("k", "p")
    print1by1(code)
    print("\n")
    tim()
    code.replace("l", "q")
    print1by1(code)
    print("\n")
    tim()
    code.replace("m", "r")
    print1by1(code)
    print("\n")
    tim()
    code.replace("n", "s")
    print1by1(code)
    print("\n")
    tim()
    code.replace("p", "t")
    print1by1(code)
    print("\n")
    tim()
    code.replace("q", "u")
    print1by1(code)
    print("\n")
    tim()
    code.replace("u", "v")
    print1by1(code)
    print("\n")
    tim()
    code.replace("v", "w")
    print1by1(code)
    print("\n")
    tim()
    code.replace("x", "x")
    print1by1(code)
    print("\n")
    tim()
    code.replace("y", "y")
    print1by1(code)
    print("\n")
    tim()
    code.replace("z", "z")
    print1by1(code)
    print("\n")
    tim()

start = input("Welcome to the Nuclear Fallout Launch Code Decoder (V 1.12.04). Type in help for assistance.")
if start.lower() == "help":
    print("Instructions: Insert code and press enter to continue. Whenever given a prompt, simply enter a code.")
code = input("Please insert code (no spaces!)")
print("Decoding...")
code = code.lower()
numTransfer = code
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p = numTransfer
a, c, e, g, i, k, m, o = code
tim()
code = ''.join([i for i in code if not i.isdigit()])
descramble()
code = input("Please descramble the following code into a pronounceable word:" + code)
descramble()
print(code.replace(a, b))
print(code.replace(c, d))
print(code.replace(e, f))
print(code.replace(g, h))
print(code.replace(i, j))
print(code.replace(k, l))
print(code.replace(m, n))
print(code.replace(o, p))
print("DECODED! Code is " + code + "!")
